### ISSUE TITLE
Issue with UI's responsibility

### ISSUE THREAD

**Issue by Seniru** [dankreiger/firebase-example-another#1]
Hello! When I run your app from my phone I got a problem with the Web page's home page. 
Here is what it's look like

![Screenshot_20190818-204205](https://user-images.githubusercontent.com/34127015/63226561-be48c100-c1f8-11e9-92e7-fded95a3e6aa.png)

**System information**
 - OS: Android
 - Device: Samsung Galaxy J2
 - Browser: Chrome for Android

**Comment by dankreiger** [comment]
@Seniru 

Hi sorry I'm only seeing this now.

If you pull from the master branch, you'll see I've updated css so it works on mobile/tablet views. So now on android it will look like this:

![Bildschirmfoto 2019-09-21 um 14 45 05](https://user-images.githubusercontent.com/5302071/65373484-76490e00-dc7e-11e9-9690-d0281a75b7cf.png)


For your information, the code in the repository is from a lengthy tutorial I was following on udemy which covers many different aspects of react, redux, firebase, gatsby, graphql, and some other topics as well. Here is a link to the tutorial if you are curious: https://www.udemy.com/complete-react-developer-zero-to-mastery/

**Comment by Seniru** [comment]
Oh OK 👍 
And thanks for the tutorial link
